# Harmony Jekyll theme general configurations 

# Base URL
baseurl: 

# Site live URL
url: http://mindlee.com

# Localhost 
#url: http://127.0.0.1:4000  

# Harmony theme configuration. Please change accordingly.
harmony:
  name: Wei Li {Terence}
  # Little description about your site
  description: 把生命浪费在美好的事物上
  # 'meta_description:' Write an awesome description for your new site here.
  # It will appear in your document head meta (for Google search results) and 
  # in your feed.xml site description.
  meta_description: 把生命浪费在美好的事物上，Terence Lee 的个人博客。
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Terence Lee
    email: liwei.day@gmail.com
    url: http://mindlee.com

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-24859308-2

  # Profile links, leave blank to ignore
  social: 
    github: welon
    twitter: chinawelon
    douban: mindlee
    facebook: 
    gplus: 
    dribble: 
    pinterest: 
  # Toggle disclaimer in footer
  show_disclaimer: true

# Conversion / Build settings 
markdown:    kramdown
# This is how you put rouge config in jekyll 3.0 instead of rouge: true
highlighter: rouge 

# Permalinks
permalink:       :year/:month/:day/:title

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: /assets/css/_sass
    style: :compressed